# Generated by Django 4.2.3 on 2023-09-23 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=10, null=True)),
                ('salary', models.FloatField(max_length=10, null=True)),
                ('image', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=300, null=True)),
                ('experience', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=70, null=True)),
                ('skills', models.CharField(max_length=100, null=True)),
                ('creationdate', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job.recruiter')),
            ],
        ),
    ]
