# Generated by Django 4.2.3 on 2023-09-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Jobs',
        ),
    ]
