# Generated by Django 4.2.3 on 2023-10-05 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0005_rename_job_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('applydate', models.DateField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job.jobs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job.studentuser')),
            ],
        ),
    ]
